
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/market?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.gmail.com
    port: 465
    username: lu1371742736@gmail.com
    password: ctzm dlei jiwl uyao


    properties:
      from: lu1371742736@gmail.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

    data:
      redis:
        database: 0
        host: localhost
        port: 6379